ts.app.name = TS common libraries
ts.app.version = 8.0.0
ts.company-name = ToxSoft LLC
ts.target-core-lib = ../../ts4-targets/ts4-target-core/lib
ts.target-core-main = ../../ts4-targets/ts4-target-core/main
ts.target-core-rcp = ../../ts4-targets/ts4-target-core/rcp
ts.target-core-rap = ../../ts4-targets/ts4-target-core/rap
ts.target-extlibs-lib = ../../ts4-targets/ts4-target-extlibs/lib
ts.target-extlibs-main = ../../ts4-targets/ts4-target-extlibs/main
ts.target-extlibs-rcp = ../../ts4-targets/ts4-target-extlibs/rcp
ts.target-extlibs-rap = ../../ts4-targets/ts4-target-extlibs/rap
ts.target-l2-lib = ../../ts4-targets/ts4-target-l2/lib
ts.target-l2-main = ../../ts4-targets/ts4-target-l2/main
ts.target-l2-rcp = ../../ts4-targets/ts4-target-l2/rcp
ts.target-l2-rap = ../../ts4-targets/ts4-target-l2/rap
ts.target-uskat-lib = ../../ts4-targets/ts4-target-uskat/lib
ts.target-uskat-main = ../../ts4-targets/ts4-target-uskat/main
ts.target-uskat-rcp = ../../ts4-targets/ts4-target-uskat/rcp
ts.target-uskat-rap = ../../ts4-targets/ts4-target-uskat/rap
ts.target-skide-lib = ../../ts4-targets/ts4-target-skide/lib
ts.target-skide-main = ../../ts4-targets/ts4-target-skide/main
ts.target-skide-rcp = ../../ts4-targets/ts4-target-skide/rcp
ts.target-skide-rap = ../../ts4-targets/ts4-target-skide/rap
ts.target-sitrol-lib = ../../ts4-targets/ts4-target-sitrol/lib
ts.target-sitrol-main = ../../ts4-targets/ts4-target-sitrol/main
ts.target-sitrol-rcp = ../../ts4-targets/ts4-target-sitrol/rcp
ts.target-sitrol-rap = ../../ts4-targets/ts4-target-sitrol/rap
ts.target-legacy-lib = ../../ts4-targets/ts4-target-legacy/lib
ts.target-legacy-main = ../../ts4-targets/ts4-target-legacy/main
ts.target-legacy-rcp = ../../ts4-targets/ts4-target-legacy/rcp
ts.target-legacy-rap = ../../ts4-targets/ts4-target-legacy/rap

ts.target-legacy-lib = ../../ts4-targets/ts4-target-legacy/lib
ts.target-legacy-main = ../../ts4-targets/ts4-target-legacy/main
ts.target-legacy-rcp = ../../ts4-targets/ts4-target-legacy/rcp
ts.target-legacy-rap = ../../ts4-targets/ts4-target-legacy/rap
